[package]
name = "harmonicon-lessons"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
accesskit = { workspace = true }
harmonicon-core = { path = "../harmonicon-core", version = "*" }
harmonicon-audio = { path = "../harmonicon-audio", version = "*" }
harmonicon-platform = { path = "../harmonicon-platform", version = "*" }
harmonicon-song = { path = "../harmonicon-song", version = "*" }
harmonicon-app = { path = "../harmonicon-app", version = "*" }
harmonicon-ui = { path = "../harmonicon-ui", version = "*" }
harmonicon-menu = { path = "../harmonicon-menu", version = "*" }
bevy = { workspace = true }
bevy_fluent = { workspace = true }

[features]
dev = ["bevy/dev", "bevy/debug", "harmonicon-audio/dev", "harmonicon-menu/dev"]
dynamic_linking = ["bevy/dynamic_linking", "harmonicon-audio/dynamic_linking", "harmonicon-menu/dynamic_linking"]
trace_tracy = ["bevy/trace_tracy", "harmonicon-audio/trace_tracy", "harmonicon-menu/trace_tracy"]

[lints]
workspace = true
