[package]
name = "harmonicon-jam"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
harmonicon-core = { path = "../harmonicon-core", version = "*" }
harmonicon-audio = { path = "../harmonicon-audio", version = "*" }
harmonicon-platform = { path = "../harmonicon-platform", version = "*" }
harmonicon-song = { path = "../harmonicon-song", version = "*" }
harmonicon-app = { path = "../harmonicon-app", version = "*" }
harmonicon-ui = { path = "../harmonicon-ui", version = "*" }
harmonicon-gameplay = { path = "../harmonicon-gameplay", version = "*" }
bevy = { workspace = true }
rand = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "backing"
harness = false

[features]
dev = ["bevy/dev", "bevy/debug", "harmonicon-gameplay/dev"]
dynamic_linking = ["bevy/dynamic_linking", "harmonicon-gameplay/dynamic_linking"]
trace_tracy = ["bevy/trace_tracy", "harmonicon-gameplay/trace_tracy"]

[lints]
workspace = true
